---
title: Why attrition, like survival, is a tricky outcome to study
author: Ben Hanowell
date: '2020-07-06'
slug: why-attrition-like-survival-is-a-tricky-outcome-to-study
bibliography: [../scholar.bib]
tags:
  - attrition is a tricky outcome
  - people analytics deadly sins
---

During the COVID-19 pandemic, many epidemiologists express concern with the over-emphasis on survival as the primary outcome of interest. After all, COVID-19 *wrecks* your lungs, in addition to all the other horrible things it can to you being a [vascular rather than respiratory disease](https://www.nytimes.com/2020/07/06/podcasts/the-daily/coronavirus-science-indoor-infection.html) [@FourNewInsights2020] that can present symptoms in almost any part of your fragile body. In addition, by focusing on survival as the primary outcome, we risk accidentally controlling for post-treatment outcomes or causal mediators, leading to biased estimates of causal effects. For similar reasons, people analysts are becoming wary of focusing on attrition as a key performance indicator of workforce management. When talking to a fellow private sector researcher about two of their projects, they brought this up, pointing out that our obsession with attrition stems from the direct link between turnover rate and cost. Because people seek to justify the budget for a workforce management team or product, they naturally turn to attrition. Yet this causes them to lose sight of the proximate mechanisms underlying that attrition. Moreover, as one participant at the 2019 Seattle People Analytics Forum mentioned, by the time attrition has happened, you've already lost them. It's not that we should never use attrition as the key outcome. But we just have to be careful when we do.

Related Amazon internal slipbox note: See 2020/07/06 children
