baseurl: "https://slipbox.hanowell.me/"
languageCode: "en-us"
title: "Hanowell's slipbox"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4
    - name: Subscribe
      url: "index.xml"

params:
  description: "Where Hanowell takes meaningful notes."
  footer: "&copy; [Ben Hanowell](https://www.linkedin.com/in/ben-hanowell/) 2020 -- 2021"

markup:
  goldmark:
    renderer:
      unsafe: true
