---
title: Has the shift to remote work accelerated flight from academia?
author: Ben Hanowell
date: '2021-08-13'
slug: has-the-shift-to-remote-work-accelerated-flight-from-academia
categories: []
tags:
  - remote work and flight from academia
---

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(emo)
```

This note inspired by three recent encounters with people from my academic days:

1. One person told me that their inbox has exploded with requests for information about becoming a UX researcher.
1. Another from a person who is looking to become a UX researcher, told his network about it, and then had a bunch of UX researchers flood _his_ inbox.
1. Yet another person I wanted to connect with person 2, and who recently became a quantitative UX researcher, and who I never thought would join industry because they are brilliant and could totally have had a better chance than, say, me (who didn't make it in academia) at making it in academia.

I wonder if the pace of social science PhDs fleeing academia for industry jobs in UX, etc, has been accelerated by the rapid shift toward remote work in the wake of the COVID-19 pandemic. Now, if you're an Assistant Prof who is tired of waiting for tenure in Oklahoma or Arizona or North Carolina, you no longer have to figure out how to move to Seattle or the Silicon Valley or LA without dramatically decreasing your quality of life due to differential housing and daycare costs. Moreover, for many fleeing academics, the two-body problem melts away with remote work.

In addition, inspired by the third friend I mentioned, I wonder if the quality of academia-to-industry job candidates has shifted due to the maturation and diversification of analyst, research, and data science job market. The friend I was speaking to is... well, she's way smarter than me. When I left academia for industry, I was in some ways a promising student, but other ways... eh, I'll be honest with you, not so much. In many ways, I figured out academia wasn't for me because, well, it wasn't for me. So is there a new crop of highly-talented academics joining industry who come in not only with graduate-level applied statistical skills and some research experience, but who compared to my crop of fleeing academics also have more experience running large research projects and doing publication-worthy analysis?

Come to think of it, I have another friend who moved into the tech industry for a little bit *and then moved back to his dream job in academia*. Perhaps his time in industry is enticing to would-be academic employers, who increasingly realize (if my numerous guest appearances before graduate students is any indicator) that many of their graduate students are bouncing out of academia for more lucrative private sector careers. So this new crop of first-tier academics may have a more diverse set of career strategies to consider than a person like me who, awesome as I and others may think am, came into industry as a second-tier or worse academician. #selfdeprication

Maybe.

Shit, I gotta up my game...

Then again, how long is all of this gonna last, really? `r emo::jis %>% dplyr::filter(name == "man shrugging: light skin tone") %>% head(1) %>% dplyr::pull(emoji)`