---
title: Are gig economy workforces harder to optimize than employees?
author: Ben Hanowell
date: '2020-06-29'
slug: are-gig-economy-workforces-harder-to-optimize-than-employees
bibliography: [../scholar.bib]
tags:
  - gig economy hard to optimize
  - gig economy
  - Often
---

This idea popped into my head the other day and I'm jotting it down for future reference: What if gig workers are harder to optimize than a traditional workforce of employees? Why might this be? The goal of optimizing a gig workforce are to have a flexible workforce on demand. Yet that presumes you are good enough at forecasting both demand and labor supply elasticity to demand to (1) fill your recruitment pipeline optimally; (2) graduate workers from the recruiting pipeline into active status; (3) make sure there is enough work to satisfy workers so you don't lose so many of them year in and year out after spending the resources to recruit them. Seems like there are a lot of moving parts here, which means there are many ways it can go wrong. In contrast, a stable pool of employees (with some seasonal temporary recruitment if necessary, and maybe a bit of a mixed strategy that includes room for some gig workers) can minimize risk by averaging over the peaks and valleys in demand. It seems much easier to predict long term trends and prepare for occasional shocks than it is to follow all the bumps and squiggles. Moreover, many of the myths about gig work suggest we are optimizing the wrong objective function anyway since gig workers often operate and are subject to the same basic constraints as employees [@stewardPerspectiveFiveMyths]. This might be a good point to make in the chapters of **Often** (my book about people analytics and event history analysis) that focus on multistate models and repeated events.
