---
title: Why COVID-19 impacts stock market differently than the rest of the economy
author: Ben Hanowell
date: '2020-06-22'
bibliography: [scholar.bib]
slug: covid-19-stock-market-isnt-economy
categories: []
tags:
  - COVID-19
  - stock market
  - US economy
---

A [recent article](https://fivethirtyeight.com/features/the-economy-is-a-mess-so-why-isnt-the-stock-market/) in FiveThirtyEight [@paineEconomyMessWhy2020] put it like this: "The stock market isn't the economy." The article's author showed that economic indicators like consumer confidence and employment to population ratio aren't tracking with the rapid recovery of stock market indicators like the S&P 500. This reminded me of a claim I heard that perhaps these indicators aren't tracking one another because decisions about the stock market are made on different time scales. Indeed, some have used this trend to make the somewhat politically-charged claim that stock investors aren't motivated by short-term interests. Yet if you read the whole FiveThiryEight article, you come up with an alternative explanation for the phenomenon, which is that wealthy people (who are spending less money right now) are parking their cash in stocks because government bonds and banks are riskier. Why so? Because very large companies like those comprising the FAANG acronym all stand to gain from the way the broader economy seems to be failing. COVID-19 has wealthy people working from home (a boon for business-to-business enterprise software market), increasing the amount and diversity of goods they have delivered (a boon for tech companies that focus on logistics and delivery), and more people than ever are getting their only source of entertainment and socialization online (boon to content delivery market, and again to the teleconferencing market).
