---
title: On the usefulness of meetings, and not just for graduate course curriculum
  planning
author: Ben Hanowell
date: '2021-08-27'
slug: on-the-usefulness-of-meetings-and-not-just-for-graduate-course-curriculum-planning
categories: []
tags:
  - R at CSDE
  - SOC 533A
---

This week, I met with [Zack Almquist](https://depts.washington.edu/zalmquist/) and [Phil Hurvitz](https://urbdp.be.uw.edu/people/philip-m-hurvitz/) to plan two inter-linked Winter Quarter courses at UW: Hurvitz's [Population Proseminar](http://staff.washington.edu/phurvitz/csde502_winter_2021/) course and my [Research Methods in Demography](https://soc.washington.edu/courses/2019/winter/soc/533/a) course. While Hurvitz's course introduces graduate students to computational tools of population research through the statistical programming interface R, my course will have graduate students apply those computational skills in their study of classical demographic methods. We met in person (we're all vaccinated and we were outside and we kept our distance from other folks and we wore masks inside), and I gotta say ... that was a really good idea.

After just a half hour meeting these two, we hashed out a reasonable plan and I feel like a have lot more direction ... not to mention a meaningful timeline of important deadlines.

Here's the plan:

1. During September, I'll design the bones of the course, including weekly lesson plan, problem sets, and the R packages and data the students will use. A lot of this work will draw on previous work from previous 533 A syllabi, syllabi from other demography courses, etc. But I'll add my own flavor based on my focus on transporting demographic methods to private and public sector use cases that the students may actually be called upon to do in their future jobs within or outside of academia. Me, Zack, and Hurvitz will review and refine, adn Hurvitz will rework his curriculum so that whatever R functions and packages that I'm using in a given week will have already been taught the week prior in his course.
1. In mid-October, I'll have complete problem sets, which I'll submit to Zack and we'll get them reviewed by a statistician for quality assurance and writing comprehensive solution sets in R Markdown.
1. By November, we'll be ready to give people a syllabus if they ask for it .. indeed they'll be able to check out the course site, which will be a work in progress, but still informative to their course decision-making!
1. Gonna have all the course code hosted on GitHub, and the course site will be a GitHub page.
1. Articles and problem solution sets will be hosted on Canvas.

Ideas for traditional pop research data sources:

1. IPUMS
1. NORC NLSY
1. Tidycensus interface to US Census data, linked to county shape files so we can do some fun mapping in problem sets

After figuring all that out, we drank some beer and talked about our favorite "space-times." I learned from this meeting that Phil Hurvitz is pretty cool. Zack's not so bad either.

Last decade, there was a big push against meetings. That push continues today, because, yeah, some meetings are totally useless or just not fun. But meetings serve a purpose. This one definitely served its purpose.

Related post: [Why attrition, like survival, is a tricky outcome to study](/post/2020/07/06/why-attrition-like-survival-is-a-tricky-outcome-to-study/)
